<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Invoicing.Test</RootNamespace>
    <AssemblyName>Invoicing.Test</AssemblyName>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="MSTest" Version="4.4.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Invoicing\Invoicing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
