//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Ecodex.WS.Model/2011/CFDI", ClrNamespace = "In.src.Cliente._2011.CFDI")]

namespace In.src.Cliente._2011.CFDI
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Avisos", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="Aviso")]
    public class Avisos : System.Collections.Generic.List<In.src.Cliente._2011.CFDI.Aviso>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aviso", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class Aviso : object
    {
        
        private System.DateTime VigenciaField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vigencia
        {
            get
            {
                return this.VigenciaField;
            }
            set
            {
                this.VigenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaServicio : object
    {
        
        private string RFCField;
        
        private int NumeroField;
        
        private string DescripcionField;
        
        private string EventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaSesion : object
    {
        
        private string RFCField;
        
        private int EstatusField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus
        {
            get
            {
                return this.EstatusField;
            }
            set
            {
                this.EstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaEstatus", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class CuentaEstatus : object
    {
        
        private string RFCField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        private int TimbresAsignadosField;
        
        private int TimbresDisponiblesField;
        
        private string[] CertificadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int TimbresAsignados
        {
            get
            {
                return this.TimbresAsignadosField;
            }
            set
            {
                this.TimbresAsignadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int TimbresDisponibles
        {
            get
            {
                return this.TimbresDisponiblesField;
            }
            set
            {
                this.TimbresDisponiblesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string[] Certificados
        {
            get
            {
                return this.CertificadosField;
            }
            set
            {
                this.CertificadosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltaEmisor", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class AltaEmisor : object
    {
        
        private string RFCField;
        
        private string RazonSocialField;
        
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoRegistroEmisor", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class ResultadoRegistroEmisor : object
    {
        
        private string RFCField;
        
        private string EstatusField;
        
        private string ClaveCertificadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Estatus
        {
            get
            {
                return this.EstatusField;
            }
            set
            {
                this.EstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ClaveCertificado
        {
            get
            {
                return this.ClaveCertificadoField;
            }
            set
            {
                this.ClaveCertificadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaValidacion : object
    {
        
        private string RFCField;
        
        private int NumeroField;
        
        private string DescripcionField;
        
        private string NodoField;
        
        private string AntecedenteField;
        
        private string SugerenciaField;
        
        private string EventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Nodo
        {
            get
            {
                return this.NodoField;
            }
            set
            {
                this.NodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Antecedente
        {
            get
            {
                return this.AntecedenteField;
            }
            set
            {
                this.AntecedenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sugerencia
        {
            get
            {
                return this.SugerenciaField;
            }
            set
            {
                this.SugerenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="Clientes")]
public interface Clientes
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/ServicioClientes/AvisosNuevos", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/AvisosNuevosResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AvisosNuevosFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AvisosNuevosFallaSesionFault", Name="FallaSesion")]
    System.Threading.Tasks.Task<RespuestaAvisosNuevos> AvisosNuevosAsync(SolicitudAvisosNuevos request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/ServicioClientes/EstatusCuenta", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/EstatusCuentaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/EstatusCuentaFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/EstatusCuentaFallaSesionFault", Name="FallaSesion")]
    System.Threading.Tasks.Task<RespuestaEstatusCuenta> EstatusCuentaAsync(SolicitudEstatusCuenta request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="Registrar", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/RegistrarFallaValidacionFault", Name="FallaValidacion")]
    System.Threading.Tasks.Task<RespuestaRegistro> RegistrarAsync(SolicitudRegistroCliente request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="AsignacionTimbres", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresFallaValidacionFault", Name="FallaValidacion")]
    [System.ServiceModel.FaultContractAttribute(typeof(In.src.Cliente._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Clientes/AsignacionTimbresFallaServicioFault", Name="FallaServicio")]
    System.Threading.Tasks.Task<RespuestaAsignacionTimbres> AsignacionTimbresAsync(SolicitudAsignacionTimbres request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudAvisosNuevos", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudAvisosNuevos
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    public SolicitudAvisosNuevos()
    {
    }
    
    public SolicitudAvisosNuevos(string RFC, string Token, long TransaccionID)
    {
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaAvisosNuevos", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaAvisosNuevos
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public In.src.Cliente._2011.CFDI.Avisos Avisos;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaAvisosNuevos()
    {
    }
    
    public RespuestaAvisosNuevos(In.src.Cliente._2011.CFDI.Avisos Avisos, long TransaccionID)
    {
        this.Avisos = Avisos;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudEstatusCuenta", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudEstatusCuenta
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    public SolicitudEstatusCuenta()
    {
    }
    
    public SolicitudEstatusCuenta(string RFC, string Token, long TransaccionID)
    {
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaEstatusCuenta", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaEstatusCuenta
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public In.src.Cliente._2011.CFDI.CuentaEstatus Estatus;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaEstatusCuenta()
    {
    }
    
    public RespuestaEstatusCuenta(In.src.Cliente._2011.CFDI.CuentaEstatus Estatus, long TransaccionID)
    {
        this.Estatus = Estatus;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudRegistroCliente", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudRegistroCliente
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public In.src.Cliente._2011.CFDI.AltaEmisor Emisor;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string RfcIntegrador;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public long TransaccionID;
    
    public SolicitudRegistroCliente()
    {
    }
    
    public SolicitudRegistroCliente(In.src.Cliente._2011.CFDI.AltaEmisor Emisor, string RfcIntegrador, string Token, long TransaccionID)
    {
        this.Emisor = Emisor;
        this.RfcIntegrador = RfcIntegrador;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaRegistro", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaRegistro
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public In.src.Cliente._2011.CFDI.ResultadoRegistroEmisor Respuesta;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionId;
    
    public RespuestaRegistro()
    {
    }
    
    public RespuestaRegistro(In.src.Cliente._2011.CFDI.ResultadoRegistroEmisor Respuesta, long TransaccionId)
    {
        this.Respuesta = Respuesta;
        this.TransaccionId = TransaccionId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudAsignacionTimbres", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudAsignacionTimbres
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public int TimbresAsignar;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public long TransaccionId;
    
    public SolicitudAsignacionTimbres()
    {
    }
    
    public SolicitudAsignacionTimbres(string RFC, int TimbresAsignar, string Token, long TransaccionId)
    {
        this.RFC = RFC;
        this.TimbresAsignar = TimbresAsignar;
        this.Token = Token;
        this.TransaccionId = TransaccionId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaAsignacionTimbres", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaAsignacionTimbres
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public long SaldoAnterior;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public int SaldoNuevo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public long TransaccionId;
    
    public RespuestaAsignacionTimbres()
    {
    }
    
    public RespuestaAsignacionTimbres(long SaldoAnterior, int SaldoNuevo, string Token, long TransaccionId)
    {
        this.SaldoAnterior = SaldoAnterior;
        this.SaldoNuevo = SaldoNuevo;
        this.Token = Token;
        this.TransaccionId = TransaccionId;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
public interface ClientesChannel : Clientes, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
public partial class ClientesClient : System.ServiceModel.ClientBase<Clientes>, Clientes
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public ClientesClient(EndpointConfiguration endpointConfiguration) : 
            base(ClientesClient.GetBindingForEndpoint(endpointConfiguration), ClientesClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ClientesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(ClientesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ClientesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(ClientesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<RespuestaAvisosNuevos> AvisosNuevosAsync(SolicitudAvisosNuevos request)
    {
        return base.Channel.AvisosNuevosAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaEstatusCuenta> EstatusCuentaAsync(SolicitudEstatusCuenta request)
    {
        return base.Channel.EstatusCuentaAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaRegistro> RegistrarAsync(SolicitudRegistroCliente request)
    {
        return base.Channel.RegistrarAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaAsignacionTimbres> AsignacionTimbresAsync(SolicitudAsignacionTimbres request)
    {
        return base.Channel.AsignacionTimbresAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PuertoClientesSeguro))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.PuertoClientes))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PuertoClientesSeguro))
        {
            return new System.ServiceModel.EndpointAddress("https://pruebas.ecodex.com.mx:2045/ServicioClientes.svc");
        }
        if ((endpointConfiguration == EndpointConfiguration.PuertoClientes))
        {
            return new System.ServiceModel.EndpointAddress("http://pruebas.ecodex.com.mx:2044/ServicioClientes.svc");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        PuertoClientesSeguro,
        
        PuertoClientes,
    }
}
