//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//InvoicingLibrary.src
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Ecodex.WS.Model/2011/CFDI", ClrNamespace= "Invo.src.Timbrado._2011.CFDI")]

namespace Invo.src.Timbrado._2011.CFDI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteXML", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class ComprobanteXML : object
    {
        
        private string DatosXMLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosXML
        {
            get
            {
                return this.DatosXMLField;
            }
            set
            {
                this.DatosXMLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AdvertenciasValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI", ItemName="AdvertenciaValidacion")]
    public class AdvertenciasValidacion : System.Collections.Generic.List<Invo.src.Timbrado._2011.CFDI.AdvertenciaValidacion>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvertenciaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class AdvertenciaValidacion : object
    {
        
        private string NodoField;
        
        private string DescripcionField;
        
        private string AntecedenteField;
        
        private string SugerenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nodo
        {
            get
            {
                return this.NodoField;
            }
            set
            {
                this.NodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Antecedente
        {
            get
            {
                return this.AntecedenteField;
            }
            set
            {
                this.AntecedenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Sugerencia
        {
            get
            {
                return this.SugerenciaField;
            }
            set
            {
                this.SugerenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaValidacion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaValidacion : object
    {
        
        private string RFCField;
        
        private int NumeroField;
        
        private string DescripcionField;
        
        private string NodoField;
        
        private string AntecedenteField;
        
        private string SugerenciaField;
        
        private string EventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Nodo
        {
            get
            {
                return this.NodoField;
            }
            set
            {
                this.NodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Antecedente
        {
            get
            {
                return this.AntecedenteField;
            }
            set
            {
                this.AntecedenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sugerencia
        {
            get
            {
                return this.SugerenciaField;
            }
            set
            {
                this.SugerenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaSesion : object
    {
        
        private string RFCField;
        
        private int EstatusField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus
        {
            get
            {
                return this.EstatusField;
            }
            set
            {
                this.EstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaServicio : object
    {
        
        private string RFCField;
        
        private int NumeroField;
        
        private string DescripcionField;
        
        private string EventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteEstatus", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class ComprobanteEstatus : object
    {
        
        private string UUIDField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private System.DateTime UltimaActualizacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UUID
        {
            get
            {
                return this.UUIDField;
            }
            set
            {
                this.UUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime UltimaActualizacion
        {
            get
            {
                return this.UltimaActualizacionField;
            }
            set
            {
                this.UltimaActualizacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionQR", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class InformacionQR : object
    {
        
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="Timbrado")]
public interface Timbrado
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXML", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLFallaValidacionFault", Name="FallaValidacion")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/TimbraXMLFallaServicioFault", Name="FallaServicio")]
    System.Threading.Tasks.Task<RespuestaTimbraXML> TimbraXMLAsync(SolicitudTimbraXML request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/CancelaTimbradoFallaValidacionFault", Name="FallaValidacion")]
    System.Threading.Tasks.Task<RespuestaCancelaTimbrado> CancelaTimbradoAsync(SolicitudCancelaTimbrado request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/EstatusTimbradoFallaValidacionFault", Name="FallaValidacion")]
    System.Threading.Tasks.Task<RespuestaEstatusTimbrado> EstatusTimbradoAsync(SolicitudEstatusTimbrado request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerTimbradoFallaValidacionFault", Name="FallaValidacion")]
    System.Threading.Tasks.Task<RespuestaObtenerTimbrado> ObtenerTimbradoAsync(SolicitudObtenerTimbrado request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbrado", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoFallaSesionFault", Name="FallaSesion")]
    [System.ServiceModel.FaultContractAttribute(typeof(Invo.src.Timbrado._2011.CFDI.FallaValidacion), Action="http://Ecodex.WS.Model/2011/CFDI/Timbrado/ObtenerQRTimbradoFallaValidacionFault", Name="FallaValidacion")]
    System.Threading.Tasks.Task<RespuestaObtenerQRTimbrado> ObtenerQRTimbradoAsync(SolicitudObtenerQRTimbrado request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudTimbraXML", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudTimbraXML
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public Invo.src.Timbrado._2011.CFDI.ComprobanteXML ComprobanteXML;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public long TransaccionID;
    
    public SolicitudTimbraXML()
    {
    }
    
    public SolicitudTimbraXML(Invo.src.Timbrado._2011.CFDI.ComprobanteXML ComprobanteXML, string RFC, string Token, long TransaccionID)
    {
        this.ComprobanteXML = ComprobanteXML;
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaTimbraXML", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaTimbraXML
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public Invo.src.Timbrado._2011.CFDI.AdvertenciasValidacion Advertencias;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public Invo.src.Timbrado._2011.CFDI.ComprobanteXML ComprobanteXML;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    public RespuestaTimbraXML()
    {
    }
    
    public RespuestaTimbraXML(Invo.src.Timbrado._2011.CFDI.AdvertenciasValidacion Advertencias, Invo.src.Timbrado._2011.CFDI.ComprobanteXML ComprobanteXML, long TransaccionID)
    {
        this.Advertencias = Advertencias;
        this.ComprobanteXML = ComprobanteXML;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudCancelaTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudCancelaTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public string UUID;
    
    public SolicitudCancelaTimbrado()
    {
    }
    
    public SolicitudCancelaTimbrado(string RFC, string Token, long TransaccionID, string UUID)
    {
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
        this.UUID = UUID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaCancelaTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaCancelaTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public bool Cancelada;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaCancelaTimbrado()
    {
    }
    
    public RespuestaCancelaTimbrado(bool Cancelada, long TransaccionID)
    {
        this.Cancelada = Cancelada;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudEstatusTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudEstatusTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public long TransaccionOriginal;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=4)]
    public string UUID;
    
    public SolicitudEstatusTimbrado()
    {
    }
    
    public SolicitudEstatusTimbrado(string RFC, string Token, long TransaccionID, long TransaccionOriginal, string UUID)
    {
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
        this.TransaccionOriginal = TransaccionOriginal;
        this.UUID = UUID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaEstatusTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaEstatusTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public Invo.src.Timbrado._2011.CFDI.ComprobanteEstatus Estatus;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaEstatusTimbrado()
    {
    }
    
    public RespuestaEstatusTimbrado(Invo.src.Timbrado._2011.CFDI.ComprobanteEstatus Estatus, long TransaccionID)
    {
        this.Estatus = Estatus;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudObtenerTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudObtenerTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public long TransaccionOriginal;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=4)]
    public string UUID;
    
    public SolicitudObtenerTimbrado()
    {
    }
    
    public SolicitudObtenerTimbrado(string RFC, string Token, long TransaccionID, long TransaccionOriginal, string UUID)
    {
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
        this.TransaccionOriginal = TransaccionOriginal;
        this.UUID = UUID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaObtenerTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaObtenerTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public Invo.src.Timbrado._2011.CFDI.ComprobanteXML ComprobanteXML;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaObtenerTimbrado()
    {
    }
    
    public RespuestaObtenerTimbrado(Invo.src.Timbrado._2011.CFDI.ComprobanteXML ComprobanteXML, long TransaccionID)
    {
        this.ComprobanteXML = ComprobanteXML;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudObtenerQRTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudObtenerQRTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=2)]
    public long TransaccionID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=3)]
    public string UUID;
    
    public SolicitudObtenerQRTimbrado()
    {
    }
    
    public SolicitudObtenerQRTimbrado(string RFC, string Token, long TransaccionID, string UUID)
    {
        this.RFC = RFC;
        this.Token = Token;
        this.TransaccionID = TransaccionID;
        this.UUID = UUID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaObtenerQRTimbrado", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaObtenerQRTimbrado
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public Invo.src.Timbrado._2011.CFDI.InformacionQR QR;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaObtenerQRTimbrado()
    {
    }
    
    public RespuestaObtenerQRTimbrado(Invo.src.Timbrado._2011.CFDI.InformacionQR QR, long TransaccionID)
    {
        this.QR = QR;
        this.TransaccionID = TransaccionID;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
public interface TimbradoChannel : Timbrado, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
public partial class TimbradoClient : System.ServiceModel.ClientBase<Timbrado>, Timbrado
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public TimbradoClient()
    {
    }
    public TimbradoClient(EndpointConfiguration endpointConfiguration) : 
            base(TimbradoClient.GetBindingForEndpoint(endpointConfiguration), TimbradoClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TimbradoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(TimbradoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TimbradoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(TimbradoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public TimbradoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<RespuestaTimbraXML> TimbraXMLAsync(SolicitudTimbraXML request)
    {
        return base.Channel.TimbraXMLAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaCancelaTimbrado> CancelaTimbradoAsync(SolicitudCancelaTimbrado request)
    {
        return base.Channel.CancelaTimbradoAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaEstatusTimbrado> EstatusTimbradoAsync(SolicitudEstatusTimbrado request)
    {
        return base.Channel.EstatusTimbradoAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaObtenerTimbrado> ObtenerTimbradoAsync(SolicitudObtenerTimbrado request)
    {
        return base.Channel.ObtenerTimbradoAsync(request);
    }
    
    public System.Threading.Tasks.Task<RespuestaObtenerQRTimbrado> ObtenerQRTimbradoAsync(SolicitudObtenerQRTimbrado request)
    {
        return base.Channel.ObtenerQRTimbradoAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PuertoTimbradoSeguro))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.PuertoTimbrado))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PuertoTimbradoSeguro))
        {
            return new System.ServiceModel.EndpointAddress("https://pruebas.ecodex.com.mx:2045/ServicioTimbrado.svc");
        }
        if ((endpointConfiguration == EndpointConfiguration.PuertoTimbrado))
        {
            return new System.ServiceModel.EndpointAddress("http://pruebas.ecodex.com.mx:2044/ServicioTimbrado.svc");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        PuertoTimbradoSeguro,
        
        PuertoTimbrado,
    }
}
