//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Ecodex.WS.Model/2011/CFDI", ClrNamespace= " Inv.src.Seguridad._2011.CFDI")]

namespace Inv.src.Seguridad._2011.CFDI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaServicio : object
    {
        
        private string RFCField;
        
        private int NumeroField;
        
        private string DescripcionField;
        
        private string EventoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento
        {
            get
            {
                return this.EventoField;
            }
            set
            {
                this.EventoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    public partial class FallaSesion : object
    {
        
        private string RFCField;
        
        private int EstatusField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC
        {
            get
            {
                return this.RFCField;
            }
            set
            {
                this.RFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus
        {
            get
            {
                return this.EstatusField;
            }
            set
            {
                this.EstatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="Seguridad")]
public interface Seguridad
{
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerToken", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Inv.src.Seguridad._2011.CFDI.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenFallaServicioFault", Name="FallaServicio")]
    [System.ServiceModel.FaultContractAttribute(typeof(Inv.src.Seguridad._2011.CFDI.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenFallaSesionFault", Name="FallaSesion")]
    System.Threading.Tasks.Task<RespuestaObtenerToken> ObtenerTokenAsync(SolicitudObtenerToken request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudObtenerToken", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class SolicitudObtenerToken
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string RFC;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public SolicitudObtenerToken()
    {
    }
    
    public SolicitudObtenerToken(string RFC, long TransaccionID)
    {
        this.RFC = RFC;
        this.TransaccionID = TransaccionID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaObtenerToken", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
public partial class RespuestaObtenerToken
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
    public string Token;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
    public long TransaccionID;
    
    public RespuestaObtenerToken()
    {
    }
    
    public RespuestaObtenerToken(string Token, long TransaccionID)
    {
        this.Token = Token;
        this.TransaccionID = TransaccionID;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
public interface SeguridadChannel : Seguridad, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
public partial class SeguridadClient : System.ServiceModel.ClientBase<Seguridad>, Seguridad
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public SeguridadClient()
    {
    }
    public SeguridadClient(EndpointConfiguration endpointConfiguration) : 
            base(SeguridadClient.GetBindingForEndpoint(endpointConfiguration), SeguridadClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SeguridadClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(SeguridadClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SeguridadClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(SeguridadClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<RespuestaObtenerToken> ObtenerTokenAsync(SolicitudObtenerToken request)
    {
        return base.Channel.ObtenerTokenAsync(request);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PuertoSeguridadSeguro))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.PuertoSeguridad))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.PuertoSeguridadSeguro))
        {
            return new System.ServiceModel.EndpointAddress("https://pruebas.ecodex.com.mx:2045/ServicioSeguridad.svc");
        }
        if ((endpointConfiguration == EndpointConfiguration.PuertoSeguridad))
        {
            return new System.ServiceModel.EndpointAddress("http://pruebas.ecodex.com.mx:2044/ServicioSeguridad.svc");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        PuertoSeguridadSeguro,
        
        PuertoSeguridad,
    }
}
